machine <- read.csv("~/R-Assignment_Econometric_methods/machine.data", header=FALSE)
names(machine) <- c("vendor", "model", "myct", "mmin", "mmax","cach", "chmin", "chmax", "prp", "erp")
mean(machine$prp)
mean(machine$mmax)
median(machine$mmax)
sd(machine$mmax)
max(machine$mmax)
min(machine$mmax)
mean(machine$prp)
median(machine$prp)
sd(machine$prp)
max(machine$prp)
min(machine$prp)
plot(machine$mmax,machine$prp,xlab="maximum main memory",ylab="prp")
plot(machine$mmax,machine$prp,xlab="maximum main memory",ylab="Published Relative Performance")
plot(machine$mmax,machine$prp,xlab="maximum main memory",ylab="Published Relative Performance",type="p")
mod1 <- lm(prp~I(mmax^2),data=machine)
smod1 <- summary(mod1)
b1 <- coef(mod1)[[1]]
b2 <- coef(mod1)[[2]]
mod1
smod1
smod1$r.squared
curve(b1+b2*x^2, col="red", add=TRUE)
median(machine$mmax)
medianValue <- median(machine$mmax)
explanatoryVal <-c(medianValue)
PredPrpVal <- b1+b2*explanatoryVal^2
PredPrpVal
newx <-c(medianValue)
yhat <- predict(mod1,newx)
newx <-data.frame(c(medianValue))
yhat <- predict(mod1,newx)
newx <-data.frame(mmax=c(medianValue))
yhat <- predict(mod1,newx)
yhat
library(xtable)
library(knitr)
table <- data.frame(round(xtable(summary(mod1)), 3))
kable(table, caption = "Regression output for the 'CPU' model")
library(knitr)
mod1 <- lm(prp~I(mmax^2),data=machine)
table <- data.frame(round(xtable(summary(mod1)), 3))
kable(table, caption = "Regression output for the 'CPU' model")
ci <- confint(mod1)
ci
b2
table <- data.frame(round(xtable(summary(mod1)), 10))
kable(table, caption = "Regression output for the 'CPU' model")
table <- data.frame(round(xtable(summary(mod1)), 12))
kable(table, caption = "Regression output for the 'CPU' model")
table <- data.frame(round(xtable(summary(mod1)), 15))
kable(table, caption = "Regression output for the 'CPU' model")
table <- data.frame(round(xtable(summary(mod1)), 7))
kable(table, caption = "Regression output for the 'CPU' model")
anov <- annov(mod1)
anov <- anova(mod1)
dfr <- data.frame(anov)
kable(dfr, caption="Output generated by the `anova` function")
sse <- anov[2,2]
ssr <- anov[1,2]
sst <- sse + ssr
sst
sse
ssr
ehat <- mod1$residuals
plot(machine$mmax, ehat, xlab="maximum main memory", ylab="residuals",type="p")
abline(0,0)
library(tseries)
ebar <- mean(ehat)
sde <- sd(ehat)
hist(ehat, col="grey", freq=FALSE, main="",
ylab="density", xlab="ehat")
curve(dnorm(x, ebar, sde), col=2, add=TRUE,
ylab="density", xlab="ehat")
jarque.bera.test(ehat)
